title: <p align="center"> Dr. Himanshu Bedi </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="https://github.com/pioneerleo">GitHub</a>
  
  <br>  
  A budding Data Scientist
  <br>
  </p>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
